# Generated by Django 2.2.13 on 2021-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210330_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
