# Generated by Django 2.2.13 on 2021-03-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210331_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_producto', to='api.Producto')),
            ],
        ),
    ]
