from .user import UserSerializer, UserReadSerializer
from .productoSerializers import ProductoSerializer, ProductoReadSerializer
from .clienteserialiser import ClienteSerializer, ClienteReadSerializer